version: "3"
services:
  redisShop:
    image: redis
    ports:
      - "16379:6379"
    container_name: redisShop

  mysqlShop:
    image: mysql
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=shopdevgo
    container_name: mysqlShop