server:
  port: 8082
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 10
  conMaxLifeTime: 3600
logger:
  log_level: debug
  file_log_name:  "./storage/logs/dev_001.log"
  max_size:    500
  max_backups: 3
  max_age:     28
  compress:   true
redis:
  host: 127.0.0.1
  port: 16379
  password:
  database: 0