server:
  port: 8082
databases:
  - user: admin1
    password: admin1
    host: localhost1
    dbName: shopDEV1
  - user: admin2
    password: admin2
    host: localhost2
    dbName: shopDEV2
security:
  jwt:
    key: abc123
